name: Deploy

on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:
  build_and_test:
    if: contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Make and deploy docs
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make Deploy Directory
      run: mkdir deploy

    - name: Copy CV
      run: cp CV/cv.pdf deploy/cv.pdf

    - name: Copy Resume
      run: cp Resume/resume.pdf deploy/resume.pdf

    - name: Deploy CV/Resume
      if: ${{ github.event_name != 'pull_request' }}
      uses: garygrossgarten/github-action-scp@release
      with:
        local: deploy
        remote: Library/Web/about
        host: ccrma-gate.stanford.edu
        username: jatin
        password: ${{ secrets.CCRMA_PASS }}
